//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRAttendance.StaffLoginUATWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WSStaffLogin/", ConfigurationName="StaffLoginUATWS.StaffLogin")]
    public interface StaffLogin {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.getErrMsgResponse getErrMsg(QRAttendance.StaffLoginUATWS.getErrMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getErrMsgResponse> getErrMsgAsync(QRAttendance.StaffLoginUATWS.getErrMsgRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.authStaffPortalResponse authStaffPortal(QRAttendance.StaffLoginUATWS.authStaffPortalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.authStaffPortalResponse> authStaffPortalAsync(QRAttendance.StaffLoginUATWS.authStaffPortalRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.valLoginEncResponse valLoginEnc(QRAttendance.StaffLoginUATWS.valLoginEncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginEncResponse> valLoginEncAsync(QRAttendance.StaffLoginUATWS.valLoginEncRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.valLoginResponse valLogin(QRAttendance.StaffLoginUATWS.valLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginResponse> valLoginAsync(QRAttendance.StaffLoginUATWS.valLoginRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.getLoginEmpNoResponse getLoginEmpNo(QRAttendance.StaffLoginUATWS.getLoginEmpNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getLoginEmpNoResponse> getLoginEmpNoAsync(QRAttendance.StaffLoginUATWS.getLoginEmpNoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.valLoginBySchResponse valLoginBySch(QRAttendance.StaffLoginUATWS.valLoginBySchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginBySchResponse> valLoginBySchAsync(QRAttendance.StaffLoginUATWS.valLoginBySchRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.valLoginByOthersResponse valLoginByOthers(QRAttendance.StaffLoginUATWS.valLoginByOthersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginByOthersResponse> valLoginByOthersAsync(QRAttendance.StaffLoginUATWS.valLoginByOthersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.getStaffDeptResponse getStaffDept(QRAttendance.StaffLoginUATWS.getStaffDeptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getStaffDeptResponse> getStaffDeptAsync(QRAttendance.StaffLoginUATWS.getStaffDeptRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        QRAttendance.StaffLoginUATWS.getStaffInfoResponse getStaffInfo(QRAttendance.StaffLoginUATWS.getStaffInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getStaffInfoResponse> getStaffInfoAsync(QRAttendance.StaffLoginUATWS.getStaffInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getErrMsg", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class getErrMsgRequest {
        
        public getErrMsgRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getErrMsgResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class getErrMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getErrMsgResponse() {
        }
        
        public getErrMsgResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authStaffPortal", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class authStaffPortalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public authStaffPortalRequest() {
        }
        
        public authStaffPortalRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authStaffPortalResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class authStaffPortalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public authStaffPortalResponse() {
        }
        
        public authStaffPortalResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valLoginEnc", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class valLoginEncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public valLoginEncRequest() {
        }
        
        public valLoginEncRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valLoginEncResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class valLoginEncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public valLoginEncResponse() {
        }
        
        public valLoginEncResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valLogin", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class valLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public valLoginRequest() {
        }
        
        public valLoginRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valLoginResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class valLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public valLoginResponse() {
        }
        
        public valLoginResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLoginEmpNo", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class getLoginEmpNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getLoginEmpNoRequest() {
        }
        
        public getLoginEmpNoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLoginEmpNoResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class getLoginEmpNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getLoginEmpNoResponse() {
        }
        
        public getLoginEmpNoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valLoginBySch", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class valLoginBySchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public valLoginBySchRequest() {
        }
        
        public valLoginBySchRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valLoginBySchResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class valLoginBySchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public valLoginBySchResponse() {
        }
        
        public valLoginBySchResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valLoginByOthers", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class valLoginByOthersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public valLoginByOthersRequest() {
        }
        
        public valLoginByOthersRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valLoginByOthersResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class valLoginByOthersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public valLoginByOthersResponse() {
        }
        
        public valLoginByOthersResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStaffDept", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class getStaffDeptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getStaffDeptRequest() {
        }
        
        public getStaffDeptRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStaffDeptResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class getStaffDeptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getStaffDeptResponse() {
        }
        
        public getStaffDeptResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStaffInfo", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class getStaffInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getStaffInfoRequest() {
        }
        
        public getStaffInfoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStaffInfoResponse", WrapperNamespace="http://WSStaffLogin/", IsWrapped=true)]
    public partial class getStaffInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WSStaffLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getStaffInfoResponse() {
        }
        
        public getStaffInfoResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StaffLoginChannel : QRAttendance.StaffLoginUATWS.StaffLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaffLoginClient : System.ServiceModel.ClientBase<QRAttendance.StaffLoginUATWS.StaffLogin>, QRAttendance.StaffLoginUATWS.StaffLogin {
        
        public StaffLoginClient() {
        }
        
        public StaffLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaffLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.getErrMsgResponse QRAttendance.StaffLoginUATWS.StaffLogin.getErrMsg(QRAttendance.StaffLoginUATWS.getErrMsgRequest request) {
            return base.Channel.getErrMsg(request);
        }
        
        public string getErrMsg() {
            QRAttendance.StaffLoginUATWS.getErrMsgRequest inValue = new QRAttendance.StaffLoginUATWS.getErrMsgRequest();
            QRAttendance.StaffLoginUATWS.getErrMsgResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).getErrMsg(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getErrMsgResponse> QRAttendance.StaffLoginUATWS.StaffLogin.getErrMsgAsync(QRAttendance.StaffLoginUATWS.getErrMsgRequest request) {
            return base.Channel.getErrMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getErrMsgResponse> getErrMsgAsync() {
            QRAttendance.StaffLoginUATWS.getErrMsgRequest inValue = new QRAttendance.StaffLoginUATWS.getErrMsgRequest();
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).getErrMsgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.authStaffPortalResponse QRAttendance.StaffLoginUATWS.StaffLogin.authStaffPortal(QRAttendance.StaffLoginUATWS.authStaffPortalRequest request) {
            return base.Channel.authStaffPortal(request);
        }
        
        public string authStaffPortal(string arg0, string arg1) {
            QRAttendance.StaffLoginUATWS.authStaffPortalRequest inValue = new QRAttendance.StaffLoginUATWS.authStaffPortalRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            QRAttendance.StaffLoginUATWS.authStaffPortalResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).authStaffPortal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.authStaffPortalResponse> QRAttendance.StaffLoginUATWS.StaffLogin.authStaffPortalAsync(QRAttendance.StaffLoginUATWS.authStaffPortalRequest request) {
            return base.Channel.authStaffPortalAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.authStaffPortalResponse> authStaffPortalAsync(string arg0, string arg1) {
            QRAttendance.StaffLoginUATWS.authStaffPortalRequest inValue = new QRAttendance.StaffLoginUATWS.authStaffPortalRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).authStaffPortalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.valLoginEncResponse QRAttendance.StaffLoginUATWS.StaffLogin.valLoginEnc(QRAttendance.StaffLoginUATWS.valLoginEncRequest request) {
            return base.Channel.valLoginEnc(request);
        }
        
        public int valLoginEnc(string arg0, string arg1) {
            QRAttendance.StaffLoginUATWS.valLoginEncRequest inValue = new QRAttendance.StaffLoginUATWS.valLoginEncRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            QRAttendance.StaffLoginUATWS.valLoginEncResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).valLoginEnc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginEncResponse> QRAttendance.StaffLoginUATWS.StaffLogin.valLoginEncAsync(QRAttendance.StaffLoginUATWS.valLoginEncRequest request) {
            return base.Channel.valLoginEncAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginEncResponse> valLoginEncAsync(string arg0, string arg1) {
            QRAttendance.StaffLoginUATWS.valLoginEncRequest inValue = new QRAttendance.StaffLoginUATWS.valLoginEncRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).valLoginEncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.valLoginResponse QRAttendance.StaffLoginUATWS.StaffLogin.valLogin(QRAttendance.StaffLoginUATWS.valLoginRequest request) {
            return base.Channel.valLogin(request);
        }
        
        public int valLogin(string arg0, string arg1) {
            QRAttendance.StaffLoginUATWS.valLoginRequest inValue = new QRAttendance.StaffLoginUATWS.valLoginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            QRAttendance.StaffLoginUATWS.valLoginResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).valLogin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginResponse> QRAttendance.StaffLoginUATWS.StaffLogin.valLoginAsync(QRAttendance.StaffLoginUATWS.valLoginRequest request) {
            return base.Channel.valLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginResponse> valLoginAsync(string arg0, string arg1) {
            QRAttendance.StaffLoginUATWS.valLoginRequest inValue = new QRAttendance.StaffLoginUATWS.valLoginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).valLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.getLoginEmpNoResponse QRAttendance.StaffLoginUATWS.StaffLogin.getLoginEmpNo(QRAttendance.StaffLoginUATWS.getLoginEmpNoRequest request) {
            return base.Channel.getLoginEmpNo(request);
        }
        
        public string getLoginEmpNo(string arg0) {
            QRAttendance.StaffLoginUATWS.getLoginEmpNoRequest inValue = new QRAttendance.StaffLoginUATWS.getLoginEmpNoRequest();
            inValue.arg0 = arg0;
            QRAttendance.StaffLoginUATWS.getLoginEmpNoResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).getLoginEmpNo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getLoginEmpNoResponse> QRAttendance.StaffLoginUATWS.StaffLogin.getLoginEmpNoAsync(QRAttendance.StaffLoginUATWS.getLoginEmpNoRequest request) {
            return base.Channel.getLoginEmpNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getLoginEmpNoResponse> getLoginEmpNoAsync(string arg0) {
            QRAttendance.StaffLoginUATWS.getLoginEmpNoRequest inValue = new QRAttendance.StaffLoginUATWS.getLoginEmpNoRequest();
            inValue.arg0 = arg0;
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).getLoginEmpNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.valLoginBySchResponse QRAttendance.StaffLoginUATWS.StaffLogin.valLoginBySch(QRAttendance.StaffLoginUATWS.valLoginBySchRequest request) {
            return base.Channel.valLoginBySch(request);
        }
        
        public int valLoginBySch(string arg0, string arg1, string arg2) {
            QRAttendance.StaffLoginUATWS.valLoginBySchRequest inValue = new QRAttendance.StaffLoginUATWS.valLoginBySchRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            QRAttendance.StaffLoginUATWS.valLoginBySchResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).valLoginBySch(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginBySchResponse> QRAttendance.StaffLoginUATWS.StaffLogin.valLoginBySchAsync(QRAttendance.StaffLoginUATWS.valLoginBySchRequest request) {
            return base.Channel.valLoginBySchAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginBySchResponse> valLoginBySchAsync(string arg0, string arg1, string arg2) {
            QRAttendance.StaffLoginUATWS.valLoginBySchRequest inValue = new QRAttendance.StaffLoginUATWS.valLoginBySchRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).valLoginBySchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.valLoginByOthersResponse QRAttendance.StaffLoginUATWS.StaffLogin.valLoginByOthers(QRAttendance.StaffLoginUATWS.valLoginByOthersRequest request) {
            return base.Channel.valLoginByOthers(request);
        }
        
        public int valLoginByOthers(string arg0, string arg1, string arg2, string arg3) {
            QRAttendance.StaffLoginUATWS.valLoginByOthersRequest inValue = new QRAttendance.StaffLoginUATWS.valLoginByOthersRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            QRAttendance.StaffLoginUATWS.valLoginByOthersResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).valLoginByOthers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginByOthersResponse> QRAttendance.StaffLoginUATWS.StaffLogin.valLoginByOthersAsync(QRAttendance.StaffLoginUATWS.valLoginByOthersRequest request) {
            return base.Channel.valLoginByOthersAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.valLoginByOthersResponse> valLoginByOthersAsync(string arg0, string arg1, string arg2, string arg3) {
            QRAttendance.StaffLoginUATWS.valLoginByOthersRequest inValue = new QRAttendance.StaffLoginUATWS.valLoginByOthersRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).valLoginByOthersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.getStaffDeptResponse QRAttendance.StaffLoginUATWS.StaffLogin.getStaffDept(QRAttendance.StaffLoginUATWS.getStaffDeptRequest request) {
            return base.Channel.getStaffDept(request);
        }
        
        public string getStaffDept(string arg0) {
            QRAttendance.StaffLoginUATWS.getStaffDeptRequest inValue = new QRAttendance.StaffLoginUATWS.getStaffDeptRequest();
            inValue.arg0 = arg0;
            QRAttendance.StaffLoginUATWS.getStaffDeptResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).getStaffDept(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getStaffDeptResponse> QRAttendance.StaffLoginUATWS.StaffLogin.getStaffDeptAsync(QRAttendance.StaffLoginUATWS.getStaffDeptRequest request) {
            return base.Channel.getStaffDeptAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getStaffDeptResponse> getStaffDeptAsync(string arg0) {
            QRAttendance.StaffLoginUATWS.getStaffDeptRequest inValue = new QRAttendance.StaffLoginUATWS.getStaffDeptRequest();
            inValue.arg0 = arg0;
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).getStaffDeptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRAttendance.StaffLoginUATWS.getStaffInfoResponse QRAttendance.StaffLoginUATWS.StaffLogin.getStaffInfo(QRAttendance.StaffLoginUATWS.getStaffInfoRequest request) {
            return base.Channel.getStaffInfo(request);
        }
        
        public string[] getStaffInfo(string arg0) {
            QRAttendance.StaffLoginUATWS.getStaffInfoRequest inValue = new QRAttendance.StaffLoginUATWS.getStaffInfoRequest();
            inValue.arg0 = arg0;
            QRAttendance.StaffLoginUATWS.getStaffInfoResponse retVal = ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).getStaffInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getStaffInfoResponse> QRAttendance.StaffLoginUATWS.StaffLogin.getStaffInfoAsync(QRAttendance.StaffLoginUATWS.getStaffInfoRequest request) {
            return base.Channel.getStaffInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<QRAttendance.StaffLoginUATWS.getStaffInfoResponse> getStaffInfoAsync(string arg0) {
            QRAttendance.StaffLoginUATWS.getStaffInfoRequest inValue = new QRAttendance.StaffLoginUATWS.getStaffInfoRequest();
            inValue.arg0 = arg0;
            return ((QRAttendance.StaffLoginUATWS.StaffLogin)(this)).getStaffInfoAsync(inValue);
        }
    }
}
